server:
  port: 8085

spring:
  datasource:
    name: test
    url: jdbc:mysql://s00-internal.advanpro.cn:3306/advanpro_oc_test_db?useUnicode=true&&characterEncoding=utf8&serverTimezone=UTC
    username: advanpro_dev_dba
    password: g5RA1ONe5VYYANnH
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-init-sqls: set names utf8mb4;
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      use-global-data-source-stat: true

mybatis:
    aliasesPackage: seed.entity
    mapperLocations: classpath:mapper/*Mapper.xml